#!/usr/bin/env bash
# Write the theme-gallery tape: one shot per built-in theme, all in one
# container run. Usage: gen-themes.sh <themes-dir> <output-tape>
set -euo pipefail
themes_dir=$1
out=$2
{
    echo "# Generated by gen-themes.sh: one overview shot per built-in theme."
    echo "Source tapes/_settings.tape"
    echo "Hide"
    echo 'Type "source /opt/shots/env/setup.sh" Enter'
    echo "Sleep 2s"
    for file in "$themes_dir"/*.toml; do
        id=$(basename "$file" .toml)
        cat <<TAPE
Type "source /opt/shots/env/theme.sh $id" Enter
Sleep 300ms
Type "termide --no-lsp" Enter
Sleep 3s
Source tapes/_overview-steps.tape
Show
Sleep 300ms
Screenshot out/themes/$id.png
Sleep 300ms
Hide
Alt+q
Sleep 1.5s
TAPE
    done
} > "$out"
